modification du workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,33 +1,69 @@
-name: iOS Build and Test
+#name: iOS Build and Test
+#
+#on:
+#  pull_request:
+#    branches:
+#      - main
+#
+#jobs:
+#  build-and-test:
+#    runs-on: macos-latest
+#
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#
+#      - name: Build and Test
+#        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
+#        with:
+#          project: SITIENS.xcodeproj
+#          scheme: SITIENS
+#          destination: 'platform=iOS Simulator,name=iPhone 16e,OS=18.4'
+#          action: test
+#          result-bundle-path: TestResults   # <- dossier simple
+#
+#      # Debug : voir ce qui a été créé dans TestResults
+#      - name: List results
+#        run: ls -R TestResults
+#
+#      - name: Process Test Results
+#        uses: kishikawakatsumi/xcresulttool@v1
+#        if: ${{ success() || failure() }}
+#        with:
+#          path: TestResults/SITIENS.xcresult   # <- adapte au vrai nom listé ci-dessus
+name: CI
 
 on:
   pull_request:
-    branches:
-      - main
+    branches: [ main ]
 
 jobs:
   build-and-test:
     runs-on: macos-latest
+    timeout-minutes: 10
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Select Xcode
+        run: sudo xcode-select -switch /Applications/Xcode_26.0.1.app
+
+      - name: Xcode version
+        run: /usr/bin/xcodebuild -version
+
+      - name: List Available Simulators
+        run: xcrun simctl list devices
+     
+      - name: Resolve Swift Package Dependencies
+        run: xcodebuild -resolvePackageDependencies -project MediStock.xcodeproj
+
       - name: Build and Test
-        uses: sersoft-gmbh/xcodebuild-action@v3.2.0
-        with:
-          project: SITIENS.xcodeproj
-          scheme: SITIENS
-          destination: 'platform=iOS Simulator,name=iPhone 16e,OS=18.4'
-          action: test
-          result-bundle-path: TestResults   # <- dossier simple
-
-      # Debug : voir ce qui a été créé dans TestResults
-      - name: List results
-        run: ls -R TestResults
-
-      - name: Process Test Results
-        uses: kishikawakatsumi/xcresulttool@v1
-        if: ${{ success() || failure() }}
-        with:
-          path: TestResults/SITIENS.xcresult   # <- adapte au vrai nom listé ci-dessus
+        run: |
+          xcodebuild clean build test \
+          -project SITIENS.xcodeproj \
+          -scheme "SITIENS" \
+          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
+          -sdk iphonesimulator \
+          -destination "platform=iOS Simulator,name=iPhone 16e,OS=18.4" \
+          ONLY_ACTIVE_ARCH=YES
